-- Recommended schema for the webgis-sampah app
-- Run this in Supabase SQL editor if your tables are not yet aligned.

create table if not exists profiles (
  id uuid primary key,
  nama text,
  role text not null check (role in ('admin', 'warga', 'transporter')),
  created_at timestamptz default now()
);

create table if not exists warga (
  id bigint generated by default as identity primary key,
  user_id uuid unique references profiles(id) on delete cascade,
  nama text not null,
  alamat text,
  no_hp text,
  location geography(Point, 4326),
  created_at timestamptz default now()
);

create table if not exists pembayaran (
  id bigint generated by default as identity primary key,
  warga_id bigint references warga(id) on delete cascade,
  status_verifikasi text not null default 'Pending' check (status_verifikasi in ('Pending', 'Disetujui', 'Ditolak')),
  created_at timestamptz default now()
);

create table if not exists sampah (
  id bigint generated by default as identity primary key,
  warga_id bigint references warga(id) on delete cascade,
  jenis text not null,
  berat numeric,
  status_pengangkutan text not null default 'Menunggu' check (status_pengangkutan in ('Menunggu', 'Diproses', 'Selesai')),
  created_at timestamptz default now()
);

create table if not exists pengangkutan (
  id bigint generated by default as identity primary key,
  warga_id bigint references warga(id) on delete cascade,
  transporter_id uuid references profiles(id) on delete set null,
  status text not null default 'proses' check (status in ('proses', 'selesai')),
  created_at timestamptz default now()
);

-- Helpful indexes for lookups used by the app
create index if not exists idx_warga_user_id on warga(user_id);
create index if not exists idx_pembayaran_warga_id on pembayaran(warga_id);
create index if not exists idx_sampah_warga_id on sampah(warga_id);
create index if not exists idx_pengangkutan_warga_id on pengangkutan(warga_id);
create index if not exists idx_pengangkutan_transporter_id on pengangkutan(transporter_id);
